# ************************************************************
# Sequel Ace SQL dump
# Version 3041
#
# https://sequel-ace.com/
# https://github.com/Sequel-Ace/Sequel-Ace
#
# Host: 127.0.0.1 (MySQL 8.0.23)
# Database: blather
# Generation Time: 2021-11-11 04:16:40 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
SET NAMES utf8mb4;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE='NO_AUTO_VALUE_ON_ZERO', SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table arguments
# ------------------------------------------------------------

LOCK TABLES `arguments` WRITE;
/*!40000 ALTER TABLE `arguments` DISABLE KEYS */;

INSERT INTO `arguments` (`id`, `description`, `explanation`, `slug`, `created_at`, `updated_at`)
VALUES
	(1,'America isn\'t a democracy. It\'s a republic.','This is like saying \"LeBron James is NOT an athlete. He\'s a basketball player. Learn the difference!\". There actually isn\'t much of a difference. A constitutional republic is a kind of democracy','america-is-not-a-democracy','2021-10-08 04:33:23','2021-10-08 04:33:23'),
	(2,'Amnesty is a slap in the face to those who waited legally','This is an appeal to suffering. It\'s like saying that the underground railroad was a bad thing because of all the slaves who waited to be legally emancipated. They think it\'s an injustice that some immigrants never had to go through the painfully tedious, and very costly process of becoming a citizen the legal way. In their minds, it\'s only fair if everyone has to suffer through the same experience.','slap-in-the-face-to-legal-immigrants','2021-10-08 04:33:30','2021-10-08 04:33:30'),
	(3,'Anti-zionism equals with anti-semitism','Hating a government isn\'t the same thing as hating the people who are forced to live under that government.','anti-zionism-is-anti-semitism','2021-10-08 04:33:31','2021-10-08 04:33:31'),
	(4,'Antifa are violent super soldiers','The overwhelming majority of domestic terrorist attacks in America are committed by right wingers.','antifa-are-violent-super-soldiers','2021-10-08 04:33:31','2021-10-08 04:33:31'),
	(5,'Antifa are weak soy boys','People who attack others because of a supposed lack of masculinity are just projecting their insecurities on to others.','antifa-are-soy-boys','2021-10-08 04:33:32','2021-10-08 04:33:32'),
	(6,'Back the blue','Worshipping authority doesn\'t make someone strong; it makes them a bitch.','back-the-blue','2021-10-08 04:33:33','2021-10-08 04:33:33'),
	(7,'Obama deported more illegals than any other president','This is just whataboutism. Trump may have deported a lot of people but what about Obama?. If the person making this argument is in favor of tougher immigration laws then shouldn\'t they like Obama?. Statistically, more people were deported from the U.S. during Obama\'s presidency than during that of any other president. That statistic was due in large part to a change in how \"deportations\" are defined rather than to an increase in the number of persons deported.','obama-built-the-concentration-camps','2021-10-08 04:33:34','2021-10-08 04:33:34'),
	(8,'Obama was an open borders marxist','Countries with the strictest borders have historically been hardcore communist countries like East Germany, USSR, North Korea, China, and Cuba.','obama-is-an-open-borders-marxist','2021-10-08 04:33:35','2021-10-08 04:33:35'),
	(9,'Boycott this company','As of 2021, conservatives have boycotted Netlix, Gillette, the NFL, the NBA, TikTok, Goodyear, Starbucks, Budweiser, Keurig, Nike, CNN, HBO and countless others.','boycott-this-company','2021-10-08 04:33:35','2021-10-08 04:33:35'),
	(10,'COVID-19 has a 99% survival rate','If every American caught COVID and 99% of them survived, that would still translate to over 3 million deaths.','its-just-the-flu-bro','2021-10-08 04:33:36','2021-10-08 04:33:36'),
	(11,'California is a socialist shit hole','California is the world\'s 5th largest economy. There are more millionaires in California than there are in any other state.','california-is-a-third-world-country','2021-10-08 04:33:36','2021-10-08 04:33:36'),
	(12,'Cancel culture','The people who complain the most about cancel culture are usually the most eager to cancel others.','cancel-culture','2021-10-08 04:33:37','2021-10-08 04:33:37'),
	(13,'Celebrities need to stay out of politics','Conservatives have absolutely no problem with celebrities being vocal about their political beliefs, so long as they agree with those beliefs.','celebrities-need-to-stay-out-of-politics','2021-10-08 04:33:37','2021-10-08 04:33:37'),
	(14,'China downplayed COVID','','china-covered-up-covid','2021-10-08 04:33:38','2021-10-08 04:33:38'),
	(15,'China must pay for COVID casualties','Thinly veiled racism. It isn\'t logical or moral to hold all or most Chinese people accountable for the actions of other Chinese people just because they belong to the same race.','china-must-pay-for-covid','2021-10-08 04:33:38','2021-10-08 04:33:38'),
	(16,'Communism is when the government does stuff that I don\'t like','Words like \"fascism\", \"communism\", \"socialism\", \"marxism\", \"totalitarianism\", and \"tyranny\" are used as catch-all terms to describe any and all situations where the government does stuff that they don\'t like.','communism-as-catch-all-term','2021-10-08 04:33:38','2021-10-08 04:33:38'),
	(17,'Conservatives are more persecuted than gay people','Conservatives never had to fight for the right to marry or not get fired because of their sexuality.','coming-out-as-conservative-is-harder-than-coming-out-as-gay','2021-10-08 04:33:42','2021-10-08 04:33:42'),
	(18,'Criminals will always find ways to get guns even if they\'re illegal','France, Germany, Britain, Belgium, the Netherlands, Australia, New Zealand, and Japan all have much stricter gun control and their rates of violent crime are much lower. Very rarely do people apply this logic to stuff that they dislike.','gun-control-does-not-work','2021-10-08 04:33:42','2021-10-08 04:33:42'),
	(19,'Defend the constitution','Most people who claim to have a fond appreciation for the constitution have never even read it. Their knowledge of anything related to the constitition is limited to whatever platitudes are currently being regurgitated by their favorite talking heads.','defend-the-constitution','2021-10-08 04:33:42','2021-10-08 04:33:42'),
	(20,'Trump can\'t be a nazi because his daugher is Jewish','Staunch segregationist Strom Thurmond had a black daughter. Thomas Jefferson fathered six children with a woman who was his slave. Does any of that make them less racist?','trump-cant-be-a-nazi-because-his-daugher-is-jewish','2021-10-08 04:33:43','2021-10-08 04:33:43'),
	(21,'All praise be to Trump for developing such a great vaccine so quickly','Donald Trump has no medical credentials. Donald Trump was an anti-vaxxer prior to becoming president.','trump-deserves-credit-for-vaccine','2021-10-08 04:33:43','2021-10-08 04:33:43'),
	(22,'Trump downplayed Covid to prevent panic','','trump-downplayed-covid-for-good-reasons','2021-10-08 04:33:43','2021-10-08 04:33:43'),
	(23,'Trump is responsible for a booming stock market','The stock market isn\'t the economy. Figures like the unemployment rate, inflation rate, and GDP are much better indicators of how strong an economy is. The stock market has been steadily increasing since the early 2010\'s. How is it that Donald Trump deserves credit for a trend that predates his presidency by several years?. Has this person given any credit to Barack Obama for increasing the stock market? If not, then why?','stock-market-at-all-time-high','2021-10-08 04:33:43','2021-10-08 04:33:43'),
	(24,'Trump is responsible for the lowest ever black unemployment rate','Donald Trump inherited a strong economy when he took office. The black unemployment rate has been steadily decreasing since 2010. The same is true for the number of food stamp recipients. How is it that Donald Trump deserves credit for a trend that predates his presidency by seven years?. Has this person given any credit to Barack Obama for lowering the black unemployment rate? If not, then why?','lowest-ever-black-unemployment','2021-10-08 04:33:44','2021-10-08 04:33:44'),
	(25,'Trump sacrificed his billionaire lifestyle to serve the people','Donald Trump didn\'t abandon his billionare lifestyle once he became president.. He still retained his billionare status and also had the added luxury of being the most powerful person in the world','trump-gave-up-his-billionaire-lifestyle','2021-10-08 04:33:46','2021-10-08 04:33:46'),
	(26,'End birthright citizenship','Thinly veiled racism. Most wouldn\'t even think twice about granting citizenship to children born here if the children were white.','end-birthright-citizenship','2021-10-08 04:33:47','2021-10-08 04:33:47'),
	(27,'Europe has more economic freedom than America','So let\'s become more like Europe?','europe-is-more-capitalist-than-america','2021-10-08 04:33:47','2021-10-08 04:33:47'),
	(28,'Europe is a socialist shit hole','Socialism is when the workers own the means of production. None of the countries in Europe meet the criteria for being socialist. Conservatives even admit this when they\'re in full blown \'own the libs\' mode','europe-is-a-socialist-shit-hole','2021-10-08 04:33:47','2021-10-08 04:33:47'),
	(29,'Feminism is cancer','Feminism is just the idea that women and men should be treated equally','feminism-is-cancer','2021-10-08 04:33:48','2021-10-08 04:33:48'),
	(30,'Fix your own country instead of moving to another one','If the pilgrims had this attitude, would America even exist today?','fix-your-problems-in-your-own-country','2021-10-08 04:33:48','2021-10-08 04:33:48'),
	(31,'Free college is a slap in the face to people that have had to pay for it','This is like saying that buying an iPhone for only $400 in 2021 is a slap in the face to all of the people who paid $5,000 for a Motorola brick in the 80\'s.','free-college-is-a-slap-in-the-face','2021-10-08 04:33:49','2021-10-08 04:33:49'),
	(32,'Free speech','The first amendment only protects you from the government; not private corporations or citizens. Everyone has a right to free speech. That doesn\'t mean that everyone is entitled to a platform to spread their speech.','free-speech','2021-10-08 04:33:52','2021-10-08 04:33:52'),
	(33,'George Soros was a nazi','Soros is a Jewish man from Hungary. Soros was 13 years old when the war ended. Soros worked as a courier during the war. He never did anything but deliver mail and some packages.','soros-was-a-nazi','2021-10-08 04:33:52','2021-10-08 04:33:52'),
	(34,'Having the government run something will turn it into the DMV','An obvious straw man. People who want the government to run health care want hospitals to be staffed with the best doctors, surgeons, nurses, and so on. No one who wants universal health care wants desk jockies and DMV type flunkies to be in charge of performing surgeries.','turn-something-into-the-dmv','2021-10-08 04:33:53','2021-10-08 04:33:53'),
	(35,'Help homeless Americans before helping illegals','People who use this argument only care about the homeless when it\'s politically convenient. Most proponents of this argument oppose spending more money to help the homeless and tend to think of people who collect welfare as moochers and junkies.','vets-before-illegals','2021-10-08 04:33:54','2021-10-08 04:33:54'),
	(36,'Higher minimum wage laws are socialist and kill jobs','Automation isn\'t necessarily a bad thing. Arguing that higher minimum wage kills jobs is like arguing that ATMs put bank tellers out of work. Technology will continue to advance regardless of how high the minimum wage is.','minimum-wage-kills-job','2021-10-08 04:33:54','2021-10-08 04:33:54'),
	(37,'I met an Uber driver and they agreed with me','Why should anyone care what some nameless, faceless Uber driver thinks? Are Uber drivers a sign of authority now?','i-met-an-uber-driver','2021-10-08 04:33:55','2021-10-08 04:33:55'),
	(38,'Identity politics is cancer','All politics is identity politics. Every politician panders to certain groups of people in exchange for votes. Why is pandering to the LGBT community considered identity politics but not when it\'s done to suburban, middle-aged housewives?','identity-politics-is-cancer','2021-10-08 04:33:57','2021-10-08 04:33:57'),
	(39,'If abortion is outlawed women won\'t get them','Many of the people who use this argument have more empathy for a five day old clump of cells than they do for actual living, breathing human beings.','ban-abortion','2021-10-08 04:33:57','2021-10-08 04:33:57'),
	(40,'If they attack you personally, it means they don\'t have a valid argument','When conservatives take a break from hurling their most well-known insults (cuck, soy boy, beta male, libtard, low IQ) they\'ll occasionally try to claim the moral high ground by using this argument.','attack-you-personally','2021-10-08 04:33:57','2021-10-08 04:33:57'),
	(41,'If you don\'t love America then leave','Does the person making this argument like all of the laws in America? The ones about guns? The ones about taxes? The ones about welfare? If not, then why does this person still live in America? Why haven\'t they left?','love-it-or-leave-it','2021-10-08 04:33:58','2021-10-08 04:33:58'),
	(42,'Illegals haven\'t suffered as much as Jews','Whenever conservatives find themselves in a situation where they have to acknowledge the oppression of minorities in America, their default response to to go to the Holocaust. [insert group] hasn\'t suffered as much as holocaust victims have therefore they\'re just looking for handouts and victim status. Oppression isn\'t a competition and just because there are disparities among how oppressed groups are doesn\'t mean that their grievances aren\'t legitimate.','illegals-have-not-suffered-as-much-as-holocaust-victims','2021-10-08 04:33:59','2021-10-08 04:33:59'),
	(43,'Impeach this','Land doesn\'t vote; people do. Those red counties in middle America have more cows than people. Conservatives have never understood the concept of population density and it shows.','impeach-this','2021-10-08 04:33:59','2021-10-08 04:33:59'),
	(44,'Islam treats women like second class citizens','This is precisely why feminists fight for women\'s rights. Only to be mocked and ridiculed by conservative men who pretend to support women\'s rights whenever the topic of Islamic immigration is broached.','islam-treats-women-like-second-class-citizens','2021-10-08 04:33:59','2021-10-08 04:33:59'),
	(45,'Jesus rose from the dead','Dead people don\'t come back to life. It\'s a pity that some functioning adults need to have this explained to them. It doesn\'t happen now even with all of the advances in medicine and technology. It certainly didn\'t happen thousands of years ago.','jesus-rose-from-the-dead','2021-10-08 04:33:59','2021-10-08 04:33:59'),
	(46,'Just because you\'re offended doesn\'t mean you\'re right','There\'s a big difference between being politically incorrect and being a jerk. Most conservatives conflate the two. Most think that being a bigoted jerk for no apparent reason makes them noble crusaders against Orwellian tyranny.','just-because-youre-offended','2021-10-08 04:33:59','2021-10-08 04:33:59'),
	(47,'Kamala Harris is a cop','Kamala Harris did work for many years as a district attorney in San Francisco. Her record as DA has been spotty. She\'s locked up people for smoking drugs that she has confessed to smoking herself. She purposely kept some prisoners locked up solely to use them as cheap labor.','kamala-is-a-cop','2021-10-08 04:34:00','2021-10-08 04:34:00'),
	(48,'Law and order must be respected','Everyone is in favor of law and order when the laws serve to benefit them. If you\'re only going to appeal to the law when it\'s advantageous for you to do so then don\'t bother doing it all.','law-and-order','2021-10-08 04:34:02','2021-10-08 04:34:02'),
	(49,'Leftists always want to win the oppression olympics','Anyone who uses the term \"oppression olympics\" most likely already has it worked out in their own head how white people are the one and onyl true victim class.','oppression-olympics','2021-10-08 04:34:02','2021-10-08 04:34:02'),
	(50,'Leftists are broke ass bums','Red states collect a lot more in welfare than blue states. The wealthiest cities in America are overwhelmingly liberal (SF, NYC, DC, LA). Conservatives even admit this when they\'re complaining about \"coastal elites.\"','leftists-are-broke','2021-10-08 04:34:02','2021-10-08 04:34:02'),
	(51,'Leftists are uber wealthy and out of touch','Owning a smart phone doesn\'t discredit anyone\'s arguments about socialism. Just like using public services doesn\'t discredit anyone\'s opinions about capitalism.','leftists-are-rich','2021-10-08 04:34:03','2021-10-08 04:34:03'),
	(52,'Liberalism is a mental disorder','This is just a cheap playground level insult.','liberalism-is-a-mental-disorder','2021-10-08 04:34:04','2021-10-08 04:34:04'),
	(53,'Lockdown orders should be disobeyed','People who use this argument will try to split hairs and say that there\'s a huge difference between things like orders, mandates, laws, legistlation, bills and so on. In reality, it\'s just a petty semantics game. It\'s a way to help ease the cognitive dissonance that comes along with blatantly disobeying the law after years of appealing to it.','defy-lockdown-orders','2021-10-08 04:34:06','2021-10-08 04:34:06'),
	(54,'Look at all of these non-white Republicans','','look-at-all-these-non-white-republicans','2021-10-08 04:34:06','2021-10-08 04:34:06'),
	(55,'Prisons have free health care therefore universal health care will turn America into a prison','Prisons have barbed wire fences. Prisons also have free health care. If you put a barbed wire fence around your home you\'ll get free health care. This is the quality of logic here.','free-health-care-is-prison','2021-10-08 04:34:07','2021-10-08 04:34:07'),
	(56,'Private businesses reserve the right to refuse service','Many who use this argument will do a complete 180 as soon as they become personally affected by a private entity refusing to do business with them. Should businesses still reserve the right to refuse service to people of certain races or ethnicities?','private-businesses-can-refuse-service','2021-10-08 04:34:10','2021-10-08 04:34:10'),
	(57,'Private tech companies are obligated to host my content','No one is under any obligation to provide a service to a total stranger. Especially if that stranger is abusing that service by posting misinformation and baseless conspiracies. People who use this argument like to play up the whole \"I\'m being censored for speaking the TRUTH!\" angle and place themselves in the same league as genuinely heroic thinkers like Galileo and Socrates. Most people who get banned from social media don\'t get banned because they\'ve unearthed some hidden, incovenient, but profound truth that will fundamentally change the way we view the world. Most people get banned because they\'re posting batshit crazy conspiracies about satanic pedo rings being run from the basements of obscure pizza parlors. Aristotle and Plato these people are not.','big-tech-is-censoring-conservatives','2021-10-08 04:34:10','2021-10-08 04:34:10'),
	(58,'Rights come from god','If rights aren\'t granted by governments, then how does this person even know that rights exist?. Rights aren\'t tangible. They can\'t be seen or touched or anything. How does the person making this argument know that they have a right to keep what they\'ve earned?. What proof do they have that rights exist independent of governments?','rights-come-from-god','2021-10-08 04:34:12','2021-10-08 04:34:12'),
	(59,'Sanctuary cities are in violation of federal law','If a deep red state like Texas decided to adopt lax gun laws that violated federal firearms laws, would the person using this argument be okay with that? Why or why not?','end-sanctuary-cities','2021-10-08 04:34:13','2021-10-08 04:34:13'),
	(60,'Section 230 needs to be repealed','Section 230 is what prevents tech companies from being held liable for threats and calls to violence that are hosted on their platforms. Getting rid of section 230 would give tech companies even more of an incentive to crack down on stuff like fake news and hate speech.','repeal-section-230','2021-10-08 04:34:13','2021-10-08 04:34:13'),
	(61,'Socialism ensures that everyone is equally miserable','The goal is to reduce misery and suffering. So that people no longer have to declare bankrupty just because they got sick. So people won\'t be burdened down by a bunch of school debt.','socialism-creates-equal-misery','2021-10-08 04:34:14','2021-10-08 04:34:14'),
	(62,'Someone I don\'t like had their products made in a sweat shop','This is grade A concern trolling. Many who use this argument are opposed to the concept of a minimum wage. But, if someone like Colin Kaepernick has his clothing made in sweatshops, then those same people who oppose minimum wage suddenly become concerned about exploitation and workers\' rights.... They\'re not objecting to sweatshops. They\'re objecting to who is using them.. When it was revealed that some of Trump\'s clothing was made in China, there was absolutely no concern for the people who worked in sweatshops.','someone-i-dont-like-had-stuff-made-in-a-sweat-shop','2021-10-08 04:34:15','2021-10-08 04:34:15'),
	(63,'States rights need to be protected against federal intrusion','The only time people even bother making this argument is when they disagree with a federal law. If the federal law is one that they already agree with, then they\'ll argue that federal law reigns supreme. Oppression is still oppression even if it\'s being committed by a local municipality instead of the federal government','states-rights-trump-federal-laws','2021-10-08 04:34:15','2021-10-08 04:34:15'),
	(64,'Systemic racism doesn\'t exist','','systemic-racism-does-not-exist','2021-10-08 04:34:15','2021-10-08 04:34:15'),
	(65,'Taxation is theft','Then let\'s stop funding police departments that kill unarmed people and get away with it.','taxation-is-theft','2021-10-08 04:34:16','2021-10-08 04:34:16'),
	(66,'Statues of Lenin and Marx need to be torn down','','tear-down-statues-of-lenin-and-marx','2021-10-08 04:34:16','2021-10-08 04:34:16'),
	(67,'Tearing down Confederate statues is erasing history','The statues would be placed in museums; not destroyed. People would still learn about history through books and classes. Most people who use this argument are perfectly okay with statues of Marx, Lenin, or Saddam Hussein being torn down. They\'re not objecting to statues being torn down; they\'re objecting to statues of people they like (Confederates) being torn down.','confederate-statues-erasing-history','2021-10-08 04:34:16','2021-10-08 04:34:16'),
	(68,'The COVID-19 vaccine is a ploy to implant us all with microchips','The COVID-19 vaccine has earned the FDA\'s seal of approval. The COVID-19 vaccine has been tested and peer reviewed by thousands of independent scientists and they\'re all coming to the same conclusion: the vaccine is safe.','covid-vaccine-is-dangerous','2021-10-08 04:34:16','2021-10-08 04:34:16'),
	(69,'The DemoKKKrats are white supremacists','The two parties switched in the 1960\'s. Most people who use this argument know that it\'s complete bullshit. If they sincerely believed it then they wouldn\'t fight so hard to preserve Confederate statues. Many who use this argument also claim that the Democratic party hates white people. So they\'re white supremacists but also hate white people?','party-of-the-kkk','2021-10-08 04:34:18','2021-10-08 04:34:18'),
	(70,'Democrats hate white people','But they\'re also allegedly white supremacists.','party-that-hates-white-ppl','2021-10-08 04:34:18','2021-10-08 04:34:18'),
	(71,'The Democratic party is communist','Most who claim that the Democratic party is communist couldn\'t even tell you what communism is if you asked them. Communism is a classless, stateless society where the workers own the means of production.','democratic-party-is-communist','2021-10-08 04:34:18','2021-10-08 04:34:18'),
	(72,'The Democratic party is corporatist','','democratic-party-is-the-corporate-party','2021-10-08 04:34:19','2021-10-08 04:34:19'),
	(73,'The left are violent anarchists','','the-left-are-anarchists','2021-10-08 04:34:19','2021-10-08 04:34:19'),
	(74,'The left wants to replace god with government','Worshipping government isn\'t a prerequisite for wanting affordable health care or decent services in exchange for paying taxes.','the-left-wants-to-replace-god-with-government','2021-10-08 04:34:19','2021-10-08 04:34:19'),
	(75,'The nazis were socialists','The Democratic People\'s Republic of Korea isn\'t really democratic even though the word \"democratic\" is in the country\'s name. The IRA aren\'t a group of Republicans just because the word \"Republican\" is in the name. There are literally hundreds of counter examples to this argument.','nazis-were-socialists','2021-10-08 04:34:19','2021-10-08 04:34:19'),
	(76,'There are only two genders. It\'s basic biology','This isn\'t what most biologists say about gender. This argument is really just concern trolling. Most people who will use this argument don\'t have any sincere appreciation for biology, or any other area of science, for that matter.','basic-biology','2021-10-08 04:34:19','2021-10-08 04:34:19'),
	(77,'Those who sacrifice liberty for security deserve neither','','never-sacrifice-liberty-for-security','2021-10-08 04:34:20','2021-10-08 04:34:20'),
	(78,'True diversity is diversity of opinion','','true-diversity-is-diversity-of-opinion','2021-10-08 04:34:20','2021-10-08 04:34:20'),
	(79,'Undocumented immigrants aren\'t paying taxes','Everyone has to pay sales tax, even those who are undocumented. Many people who use this argument claim that taxation is theft. It\'s strange that they decide to ally themselves with the IRS whenever the victim of theft (taxation) is a person that they don\'t like.','undocumented-immigrants-arent-paying-taxes','2021-10-08 04:34:20','2021-10-08 04:34:20'),
	(80,'Undocumented immigrants don\'t have any rights because they aren\'t citizens','Every human has rights.','undocumented-immigrants-dont-have-any-rights','2021-10-08 04:34:21','2021-10-08 04:34:21'),
	(81,'Victim culture is toxic','Many people are legitimate victims of oppression. Being expected to wear a mask in order to prevent the spread of infectious diseases is not oppression. Censoring misinformation that has the potential to have real world consequences is not oppression. Conservatives have a laundry list of things that they\'re victims of: multiculturalism, censorship, the liberal media, communists... the list goes on.','ppl-are-dying-to-be-victims','2021-10-08 04:34:21','2021-10-08 04:34:21'),
	(82,'We\'re the silent majority','This is demonstrably false. Trump lost the popular vote in both the 2016 and 2020 elections. Trump lost by more than seven million votes in 2020.','silent-majority','2021-10-08 04:34:21','2021-10-08 04:34:21'),
	(83,'Weed should be legal. How could I be a Republican?','Supporting weed legalization would have earned you some progressive clout if it were still 1967 you were kicking it in Haight-Ashbury. But, it\'s 2021 already and even Mississippi, of all states, has decriminalized marijuana. If you want some bonafide left wing cred nowadays, you need to do a lot more than just support legalizing weed. A lot of people who use this argument think that supporting weed legalization is a license to spew conservative talking points ad nauseam without ever being called out.','weed-should-be-legal-so-im-cant-be-a-republican','2021-10-08 04:34:23','2021-10-08 04:34:23'),
	(84,'Welfare recipients should have to take drug tests','This is much more about hating on poor people than it is about balancing the budget. The amount of money that\'s spent on social services is dwarfed in comparison to the amount that\'s spent on the military and corporate subsidies. If someone was genuinely concerned about cutting spending or balancing the budget they\'d start with those two sectors first. A strange hill to die on, for sure.','welfare-recipients-should-have-to-take-drug-tests','2021-10-08 04:34:23','2021-10-08 04:34:23'),
	(85,'You aren\'t entitled to anything','This is a completely vacuous thing to say. There isn\'t a single thing that human beings are entitled to? Not one?. Likely projection on behalf of the person saying it. They\'re entitled but feel guilty about it so they unload that anger on to easy targets as a way of assuaging their guilt.','you-arent-entitled-to-anything','2021-10-08 04:34:23','2021-10-08 04:34:23'),
	(86,'You have low IQ','People with high IQs generally don\'t brag about their IQs. Intelligence is something that\'s more demonstrated than said. If you\'re truly intelligent, you shouldn\'t have to go around telling others that you\'re intelligent. People who brag about their supposed high IQs or who put others down for supposedly having low IQs are almost certainly projecting. Anyone who uses this argument almost definitely has a case of Dunning-Kruger.','low-iq','2021-10-08 04:34:23','2021-10-08 04:34:23'),
	(87,'You keep your front door locked but you support open borders','Homes and countries aren\'t the same things. This should be obvious to almost everyone. A person can own a home and the owner can decide who gets to come in and out of his/her property. A person cannot own a country.','you-put-locks-on-your-front-doors','2021-10-08 04:34:24','2021-10-08 04:34:24'),
	(88,'You shouldn’t have to reveal private health info in order to participate in society','Anti-vaxxers will often use this argument in regards to having to provide proof of COVID vaccinations.','proof-of-covid-vaccines','2021-10-08 04:34:25','2021-10-08 04:34:25');

/*!40000 ALTER TABLE `arguments` ENABLE KEYS */;
UNLOCK TABLES;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
